### PR TITLE
Attempt to fix https://github.com/yelouafi/redux-saga/issues/152

### PR DESCRIPTION
**Pull request by slorber**

### CODE REVIEW

**Comment by yelouafi** [comment]
thanks; I'll have also to fix `cps`, an the most subtle one which is `fork`

**Comment by yelouafi** [comment]
FYI pushed the fix. In the case of fork, I fail the forked task 

https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L318-L322

https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L125-L127

**Comment by slorber** [comment]
great :)

**Comment by yelouafi** [comment]
FYI https://github.com/yelouafi/redux-saga/releases/tag/v0.9.3

**Comment by slorber** [comment]
thanks will update

**Pull request merged**
