### PR TITLE
Add recipe for retrying XHRs

### PR DESCRIPTION
**Pull request by nuc**
Hey there,

Based on that discussion: https://github.com/yelouafi/redux-saga/issues/349 I added an example for retrying XHRs.

I also added a second example for unlimited retries, for which I'd like some feedback if you think that it won't work as expected.

Thanks!

### CODE REVIEW

**Comment by apfelfabrik** [comment]
Any feedback on this? If this is the recommended way to do retries, it should probably be in the recipes, if this is not the recommended way some suggestions for improvement would be great.

**Comment by yelouafi** [comment]
Thanks and sorry for the delay.

**Comment by juanibiapina** [comment]
One further extension to this recipe could be a way to extract the retry logic for reusability. It's a little cumbersome to duplicate this logic the way it is now.

**Comment by Andarist** [comment]
this should work
```javascript
function* retry(maxTries, saga, ...args) {
	let tries = 0

	while (true) {
		tries++

		try {
			const result = yield call(saga, ...args)
			return result
		} catch (err) {
			if (tries === maxTries) {
				throw err
			}
		}
	}
}
```

**Comment by nuc** [comment]
Would it make sense to add it to `internal/utils`, similarly as `delay`?

**Comment by Andarist** [comment]
Yeah, it would certainly make sense. However I think its more appropriate as a helper (like `takeEvery` etc) than as util.

**Comment by nuc** [comment]
Cool! I can prepare something. Cheers

**Comment by aghreed** [comment]
Anything come of this yet? I'm also looking to have a reusable "retry", and it would be pretty neat if it were baked into the library as a helper. Happy to help contribute if you'd like as well.

**Comment by Andarist** [comment]
Contribution would be greatly appreciated!

**Pull request merged**
