### PR TITLE
[TypeScript] Added actionDispatched to Monitor interface

### LINKED ISSUE #700: [TypeScript] Update Monitor Interface for 0.13 changes
[Monitor Interface](https://github.com/yelouafi/redux-saga/blob/master/index.d.ts#L18) is missing `actionDispatched` from #609

### PR DESCRIPTION
**Pull request by CarsonF**
Per #609

Fixes #700

### CODE REVIEW

**Comment by Andarist** [comment]
cc @aikoven

**Comment by aikoven** [comment]
👍

**Comment by aikoven** [comment]
Oh wait, more accurate would be `actionDispatched<A extends Action>(action: A)`

**Comment by CarsonF** [comment]
@aikoven better now?

**Comment by aikoven** [comment]
It's good now. Thanks

**Comment by CarsonF** [comment]
I'm curious what the difference is there?

**Comment by aikoven** [comment]
That's just how it's done in Redux: https://github.com/reactjs/redux/blob/v3.6.0/index.d.ts#L46

I'm not sure if it adds any strictness right now, but I think that it describes the function contract more precisely. In TypeScript saying that something has interface `T` doesn't always mean that it has properties from `T`. Sometimes it means that there are no other properties that aren't in `T`, e.g.:
```ts
interface T {
  prop: string;
}

// this would fail:
const t: T = {prop: 'foo', otherProp: 'bar'};
```
However, I can't think of any non-exotic case like this for `Monitor.actionDispatched`.

**Pull request merged**
