### PR TITLE
Make real-world example work again

### PR DESCRIPTION
**Pull request by prashaantt**
I tried the real-world example and couldn't get it to compile or run without making these changes.

### CODE REVIEW

**Comment by prashaantt** [comment]
My bad, I just noticed that `examples/real-world` has its own `package.json`. But I was misled by the `real-world` script in the root `package.json` that somehow made me believe I should be able to run it from root itself.  Perhaps you could remove it from there to prevent this confusion.

**Comment by yelouafi** [comment]
>Perhaps you could remove it from there to prevent this confusion.

Yes. I think you're right

**Comment by prashaantt** [comment]
I just found a better way to handle this:

```json
// package.json in root

"scripts": {
  "real-world": "npm --prefix examples/real-world install examples/real-world"
}
```

I'll submit a new PR if you like it.

**Comment by yelouafi** [comment]
>I'll submit a new PR if you like it.

Of course. Thanks!

**Pull request closed without merging**
