### PR TITLE
fix is.generator test

### LINKED ISSUE #10: redux-saga + webpack + uglifyjs: Saga must be a Generator function
First I would like to say that I am exiting about redux-saga.

I faced problem with redux-saga + webpack + uglifyjs combination in production build. For some reason sagas are "too well" uglified and don't pass the check utils.is.generator(saga). In result it throws and an error "Saga must be a Generator function"

I found a workaround. Just simple use such options:
new webpack.optimize.UglifyJsPlugin({
        mangle: {except: ['GeneratorFunction'] }
})

Hope it helps someone. Is there any better way to avoid such errors?

### PR DESCRIPTION
**Pull request by yelouafi**
fix issue with minified bundles (regenerator runtime's Generator function names got mangled by uglify)

should fix #10

### CODE REVIEW

**Comment by yelouafi** [comment]
>Can we just call the function and assert that it returns something with .next()?

Yes. I think this is the best thing we can do

**Comment by yelouafi** [comment]
@bgerm I released a new patch version on npm with the fix suggested by @gaearon. Could you try and confirm if it's ok now ?

**Comment by bgerm** [comment]
Thanks, @yelouafi.  Works great.

**Comment by yelouafi** [comment]
Great! I'll close the issue. Thanks!

**Pull request merged**
