### PR TITLE
Gitbook Setup

### PR DESCRIPTION
**Pull request by cef62**
Pull request related to yelouafi/redux-saga#70.

I've splitted the main readme in smaller chapters. At the moment I haven't changed or added contents. All new files are in `docs` folder, for now I've let untouched the main readme file.
I've added complete setup and configuration to compile gitbook. 
New *npm scripts*:

* `docs:build` compile gitbook to `_book` folder
* `docs:watch` compile gitbook and serve it from [localhost:4000](http://localhost:4000)
* `docs:publish` compile gitbook and publish it to github pages at [yelouafi.github.io/redux-saga](http://yelouafi.github.io/redux-saga). You can have a preview on my [fork](http://cef62.github.io/redux-saga)

The current file subdivision is hypothetical, if you'd like it as starting point I think you can merge the PR, otherwise let me know what change to make the PR acceptable.

I've used version 2.5.2 of gitbook because newer versions have issues using the main summary in a subfolder, as I've done in `book.json`.
You can follow [here](https://github.com/GitbookIO/gitbook/issues/1029) the related issue.

If you like this setup we can start working on real contents. 
I think maybe we should draft a more official TOC. Then we can subdivide the work on different chapters.

### CODE REVIEW

**Comment by yelouafi** [comment]
Great thanks for this @cef62 

>he current file subdivision is hypothetical, if you'd like it as starting point I think you can merge the PR, otherwise let me know what change to make the PR acceptable.

l prefer to take it as a starting point. It's good to have something concrete.

>If you like this setup we can start working on real contents. 
I think maybe we should draft a more official TOC. Then we can subdivide the work on different chapters.

Agree, I think the one in your actual setup makes a good starting point; thinking of adding the sections mentioned in #70; merged with the actual setup; it'll give something like

- Introduction
- Step by step tutorial
- Basics
- Advanced
- Unit testing
- Recipes (e.g. authorization, infinite scroll, integration with router, ...)
- Common Concurrency Patterns (also see https://github.com/yelouafi/redux-saga/issues/50#issuecomment-179376628)
- Troubleshooting
- Links to external resources
- Glossary
- API reference
- Contribute

What do you think ?

**Comment by yelouafi** [comment]
Ok done: http://yelouafi.github.io/redux-saga/

there was an issue with `docs:publish`. I get the following error (seems to occur after `cd _book && git init`)

```
Initialized empty Git repository in C:/My data/Yassine/projects/redux-saga/_book/.git/
error: pathspec 'book'' did not match any file(s) known to git.
```

I managed to publish by running all the steps in `docs:publish` manually

**Comment by cef62** [comment]
Great @yelouafi! 

> there was an issue with docs:publish.
I've run the script on OSX, I'll try to investigate what is different on windows and fix it.

I think your draft for the TOC is good!
Now we should improve and expand current contents.
This night I'll add more thoughts on the topic :)

**Comment by gaearon** [comment]
@cef62 Thank you for your work on this, it is greatly appreciated!

**Comment by cef62** [comment]
Thanks! I really think this library is awesome and I'm trying to contribute to it as I can.

**Pull request merged**
