### PR TITLE
Use spawn instead of fork in root saga and add fake error handling so…

### PR DESCRIPTION
**Pull request by granmoe**
… that a failed call doesn't make app unresponsive

### CODE REVIEW

**Comment by granmoe** [comment]
To kill the app and see this issue, put a debugger right before the call to reddit and replace the URL with something that will fail.

**Comment by Andarist** [comment]
One thing I dont understand - why did you change `fork`s to `spawn`s?

**Comment by slorber** [comment]
@Andarist to avoid killing all the sagas on any single http call error

Related to https://github.com/yelouafi/redux-saga/issues/570

**Comment by Andarist** [comment]
@slorber 
but that is already handled by `try/catch` over `yield call(fetchPosts, reddit)`

**Comment by slorber** [comment]
That's right @Andarist :) still I believe sagas should be isolated from each others, it's easy to forget catching errors and make your whole app unusable

**Comment by granmoe** [comment]
@Andarist @slorber Yes, I am handling all errors in the try/catch because the catch just swallows them and doesn't re-throw. I think to make the example more clear, I could handle certain types and then re-throw the rest. My intent here is to show some more nuanced error handling and clarify the fact that if you just fork all sagas, any unhandled exception will kill them all (this was a stumbling block for me in learning saga). I'm very very open to suggestions, but this example caused confusion for me when I was a newcomer to saga (which, granted, was only like two months ago).

**Comment by granmoe** [comment]
Or maybe we should be using the `task.done.catch` feature in the root saga? Mainly, I just want this example to highlight a good, idiomatic pattern for the problem of top level exception handling / not killing all your sagas on an unhandled exception.

**Comment by granmoe** [comment]
Would something like this work for centralized error handling in all sagas in an app?

```
function* rootSaga () {
  yield sagas.map(saga =>
    spawn(function* () {
      while (true) {
        try {
          yield call(saga)
        } catch (e) {
          console.log(e)
        }
      }
    })
  )
}
```

Or would it possibly cause complex bugs due to scheduling issues internal to redux-saga? I'm wondering if something could get messed up going from the catch back to the try. Assuming this all happens synchronously, there should be no problem, right? Or wrong?

**Comment by slorber** [comment]
@granmoe uncatched errors are automatically logged as far as I know so it's not really worthy to catch just for logging unless you customize error message

There are multiple ways that you can do.

Personnally in my app I'm simply doing:

```
    sagas.forEach(saga =>
      runSaga(saga,reduxSagaIO)
    );
```

**Comment by granmoe** [comment]
Sorry, my console.log is just an example (a confusing one)! We will be sending uncaughts through an error monitoring service. What is 'runSaga' and 'reduxSagaIO' in your example?

**Comment by granmoe** [comment]
Nevermind, I found runSaga in the docs

**Comment by granmoe** [comment]
I would still be curious to see your reduxSagaIO. And does this approach kill a saga that throws an uncaught exception? Or do you handle that in reduxSagaIO?

**Comment by slorber** [comment]
@granmoe I have a special setting, because I actually make Redux-saga work on top of a legacy framework I have that is not redux (we'll migrate someday to redux)

**Comment by granmoe** [comment]
OK, I pushed a new commit with my top level error handling solution. My only concern is if a situation happens, somehow, where calling the saga itself triggers an exception synchronously, how should that be handled? Maybe something like this to prevent infinite synchronous exceptions from a saga?

```
  yield sagas.map(saga =>
    spawn(function* () {
      let hasError = false
      while (!hasError) {
        try {
          setTimeout(() => { hasError = false }, 0)
          yield call(saga)
        } catch (e) {
          hasError = true
          handleError(e)
        }
      }
      throw new Error('Unrecoverable exception thrown while spawning saga', saga)
    })
  )
```

**Comment by granmoe** [comment]
I'm kind of questioning this whole idea now. Maybe it would be better to rip out the `while (true)` that I have at the top here and instead just send the error to whatever logging/monitoring service you want to use and then re-throw. Handle network errors at the source and don't ever throw anything in a saga that you don't explicitly handle.

**Comment by granmoe** [comment]
I'm going to close this for now and possibly come back to it. It would be great to get a consensus from the community regarding the right approach here.

**Pull request closed without merging**
